import { ArrowLeft } from 'lucide-react';
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function DocumentLayout({ children }: { children: React.ReactNode }) {
	return (
		<div className="bg-background py-5">
			<div className="mx-auto max-w-3xl">
				<div className=" mb-4 flex items-center gap-2 text-sm text-muted-foreground">
					<ArrowLeft size={16} />
					<Link href="/docs" className="text-slate-300 hover:text-slate-300/80">
						Back to docs
					</Link>
				</div>
				<div className="border bg-card rounded-2xl border-slate-700 p-8 shadow-sm md:p-12 mt-4">{children}</div>
				<p className="text-muted-foreground mt-6 text-center text-xs">© {new Date().getFullYear()} DepShield. All rights reserved.</p>
			</div>
		</div>
	);
}
