import { ArrowLeft } from 'lucide-react';
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function DocumentLayout({ children }: { children: React.ReactNode }) {
	return (
		<div className="min-h-screen px-6 py-8">
			<div className="mx-auto max-w-3xl">
				{/* Back link */}
				<Link
					href="/docs"
					className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors mb-6"
				>
					<ArrowLeft size={14} />
					Back to docs
				</Link>

				{/* Content card */}
				<div className="bg-card border border-border rounded-2xl p-8 md:p-12">{children}</div>

				{/* Footer */}
				<p className="text-muted-foreground mt-6 text-center text-xs">© {new Date().getFullYear()} DepShield. All rights reserved.</p>
			</div>
		</div>
	);
}
